namespace GitHubReadmeWebTrends.Functions
{
    static class PullRequestConstants
    {
        public const string BodyText =
@"We've updated the Readme!

### What is this?

To best understand which topics are popular and which subjects are trending in our developer communities, we can leverage [Web Trends](https://www.webtrends.com).

This PR was generated by an [automated open-source](https://github.com/brminnick/GitHubReadmeWebTrends) tool that double checks each Readme to ensure each repository is leveraging [Web Trends](https://www.webtrends.com).

[Web Trends](https://www.webtrends.com) does not collect any Personally Identifiable Information and cannot be traced back to any individual user.

### How do I opt-out from the tool?

You may opt-out from future PRs here: https://optout-githubreadmelinks.azurewebsites.net";
    }
}
