name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
  Build_GitHubReadmeWebTrends_Functions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET Core v6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Setup .NET Core v3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'


    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build ./GitHubReadmeWebTrends.Functions -c Release

  Build_AzureAdvocates_Functions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET Core v6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Setup .NET Core v3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build ./AzureAdvocates.Functions -c Release

  Build_GitHubReadmeWebTrends_Console:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET Core v6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Setup .NET Core v3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build ./GitHubReadmeWebTrends.Console -c Release

  Build_GitHubReadmeWebTrends_Website:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET Core v6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Setup .NET Core v3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build ./GitHubReadmeWebTrends.Website -c Release

  Run_GitHubReadmeWebTrends_UnitTests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET Core v6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Setup .NET Core v3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Inject Token
      env:
        TOKEN: ${{ secrets.TOKEN }}
      
      run: |
        GitHubConstantsFile=`find . -name GitHubConstants.cs | head -1`
        echo GitHubConstantsFile = $GitHubConstantsFile

        sed -i '' s/GitHubToken = \"\"/GitHubToken = \"$TOKEN\"/g $GitHubConstantsFile

    - name: Run Unit Tests
      run: |
        dotnet test ./GitHubReadmeWebTrends.UnitTests -c Release
